spring.application.name=sena-backend

server.port=8080
server.address=0.0.0.0

spring.datasource.url=jdbc:mysql://localhost:3306/sena_db?useSSL=false&serverTimezone=America/Mexico_City&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
groq.api.key=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

spring.jackson.time-zone=America/Mexico_City
